<?php
/**
 * @file
 * hospice_history.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function hospice_history_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function hospice_history_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function hospice_history_node_info() {
  $items = array(
    'history' => array(
      'name' => t('History'),
      'base' => 'node_content',
      'description' => t('Add Milestones to the Our History section'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
