<?php
/**
 * @file
 * hospice_history.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function hospice_history_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-history-field_milestone'
  $field_instances['node-history-field_milestone'] = array(
    'bundle' => 'history',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'field_collection',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_fields',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'fences_wrapper' => 'div',
    'field_name' => 'field_milestone',
    'label' => 'Milestone',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Milestone');

  return $field_instances;
}
